import type { Metadata } from "next";
import "./globals.css";
import { inter } from "@/lib/fonts";
import { ThemeProvider } from "@/components/theme-provider";
import ToggleTheme from "@/components/toggle-theme";

export const metadata: Metadata = {
  title: "MyLinkInBio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" suppressHydrationWarning>
      <body
        className={`${inter.className} antialiased dark:bg-neutral-900 min-h-screen`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="p-5 max-w-screen-2xl mx-auto">{children}</div>
          <ToggleTheme />
        </ThemeProvider>
      </body>
    </html>
  );
}
